{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: aiboo-redis
  labels:
    app.kubernetes.io/name: aiboo-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: aiboo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aiboo-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: redis
      port: 6379
      targetPort: redis
{{- end }}
